### ISSUE TITLE
Portuguese Brazil subtitles

### ISSUE THREAD

**Issue by infini667** [davidde/mpv-autosub#18]
hi! thanks for the script! I just can't figure it out how to configure for pt-br subs. pt is working for portuguese (portugal), but I tried pt-br, ptbr, pob, pb, pbr, br... nothing works to find portuguese brazil subtitles... :( thanks

**Comment by SpukoBR** [comment]
Hello, I put it that way and it worked for me, remembering that Brazilian Portuguese does not have ISO-639-2.

`            { 'Brazilian Portuguese', 'pt-br'},
![image](https://user-images.githubusercontent.com/83892026/117557943-dc9ac400-b04e-11eb-84dd-35689779e4f8.png)
`

I am also Brazilian, the only problem I had in some situations is synchronization, but then just open the subtitle file and see what time the first speech was, and try to regulate it using Z and X.

**Comment by davidde** [comment]
Thanks for the quick solution @SpukoBR.
