### ISSUE TITLE
Name Collision

### ISSUE THREAD

**Issue by alivefromupstairs** [davidde/mpv-autosub#6]
Instead of overwriting files, append `.num` to the file name. Ex:
`naked.lunch.1991.en.srt` => `naked.lunch.1991.en.1.srt` &  `naked.lunch.1991.en.2.srt`. (also, check if there are already numbered subs.)
This works with **`mpv`** and `vlc` with `srt` files. I have not tested other formats and video players.

Also, could you, please, add the repo link to the description of the script and some sort of versioning (in the README as well)? the script name is widely used.

Is there a way to make the script's output less verbose in the terminal? (not shut it entirely.)

**Comment by davidde** [comment]
I don't really see why it would be useful to keep multiple subtitles of the same language? Either the subtitle is ok and you keep it, or it isn't, and you delete or overwrite it. But if the overwriting bothers you, you can turn it off by setting the `force` bool in the script to false.

To make the script's output less verbose in the terminal, turn debugging off by setting the `debug` bool to false.

I've added the repo link in the readme title.
