### ISSUE TITLE
Keybindings don't work

### ISSUE THREAD

**Issue by wedens** [davidde/mpv-autosub#7]
In "manual" mode keybindings don't work because `directory` and `filename` variables in `download_subs` are undefined.

I suppose this part of `control_downloads` should be done for manual invocations too:
```lua
    -- Make MPV accept external subtitle files with language specifier:
    mp.set_property('sub-auto', 'fuzzy')
    -- Set subtitle language preference:
    mp.set_property('slang', languages[1][2])
    mp.msg.warn('Reactivate external subtitle files:')
    mp.commandv('rescan_external_files')
    directory, filename = utils.split_path(mp.get_property('path'))
```

Also, changing bindings to use `control_downloads` is not a good option as if you trigger it manually, you most likely want to download subtitles regardless of video length, name, etc.

**Comment by davidde** [comment]
I'm sorry but I can't reproduce this. My keybindings work fine. What exactly do you mean by "manual" mode?

Note that the `directory` and `filename` variables in `control_downloads` are global, so it is not necessary to repeat their declaration in `download_subs`.

**Comment by davidde** [comment]
I'm guessing you modified the script and commented out the bottom line that invoked `control_downloads`.

If that is the case you should undo that comment, and simply change the `auto` bool in the settings to false. That is the proper way to disable the automatic downloading.
